In [12]:
import pandas as pd
import numpy as np

print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)

Pandas version: 3.0.5
NumPy version: 2.5.1

In [13]:
data = {
    "Name":["John","Alice","Mike"],
    "Age":[22,25,20]
}

df = pd.DataFrame(data)

print(df)

    Name  Age
0   John   22
1  Alice   25
2   Mike   20

In [14]:
data = {
    "Name":["John","Alice","Mike"],
    "Age":[22,25,20]
}

df = pd.DataFrame(data)

print(df)

    Name  Age
0   John   22
1  Alice   25
2   Mike   20

In [15]:
df["Age"]

0    22
1    25
2    20
Name: Age, dtype: int64

In [16]:
df[["Name","Age"]]

    Name  Age
0   John   22
1  Alice   25
2   Mike   20

In [17]:
df.iloc[0]

df.loc[0]

Name    John
Age       22
Name: 0, dtype: object

In [18]:
df["Age After 5 Years"] = df["Age"] + 5

In [19]:
df.drop(columns=["Age After 5 Years"])

    Name  Age
0   John   22
1  Alice   25
2   Mike   20

In [20]:
df.sort_values("Age")

    Name  Age  Age After 5 Years
2   Mike   20                 25
0   John   22                 27
1  Alice   25                 30

In [21]:
df.reset_index(drop=True)

    Name  Age  Age After 5 Years
0   John   22                 27
1  Alice   25                 30
2   Mike   20                 25